import{hasSupabase,supabase}from'./supabase';import{fallbackCountries,fallbackLocations,fallbackMedia,fallbackSettings}from'./fallback';
export async function loadPublicData(){if(!hasSupabase)return{countries:fallbackCountries,locations:fallbackLocations,media:fallbackMedia,settings:fallbackSettings,usingFallback:true};const[cr,lr,mr,sr]=await Promise.all([supabase.from('countries').select('*').eq('is_published',true).order('route_order'),supabase.from('locations').select('*').eq('is_published',true).order('sort_order'),supabase.from('media').select('*').order('sort_order'),supabase.from('site_settings').select('*').eq('id','main').limit(1)]);if(cr.error||lr.error||mr.error||sr.error)return{countries:fallbackCountries,locations:fallbackLocations,media:fallbackMedia,settings:fallbackSettings,usingFallback:true,error:cr.error||lr.error||mr.error||sr.error};return{countries:cr.data?.length?cr.data:fallbackCountries,locations:lr.data||[],media:mr.data||[],settings:sr.data?.[0]||fallbackSettings,usingFallback:false}}
export async function updateCountry(country){if(!hasSupabase)throw new Error('Supabase is not configured');return supabase.from('countries').upsert(country).select().single()}
export async function addLocation(location){if(!hasSupabase)throw new Error('Supabase is not configured');return supabase.from('locations').insert(location).select().single()}
export async function updateLocation(location){if(!hasSupabase)throw new Error('Supabase is not configured');return supabase.from('locations').upsert(location).select().single()}
export async function deleteLocation(id){if(!hasSupabase)throw new Error('Supabase is not configured');return supabase.from('locations').delete().eq('id',id)}
export async function updateSettings(settings){if(!hasSupabase)throw new Error('Supabase is not configured');return supabase.from('site_settings').upsert({id:'main',...settings,updated_at:new Date().toISOString()}).select().single()}
export async function addMedia(media){if(!hasSupabase)throw new Error('Supabase is not configured');return supabase.from('media').insert(media).select().single()}
export async function deleteMedia(id){if(!hasSupabase)throw new Error('Supabase is not configured');return supabase.from('media').delete().eq('id',id)}
