export const fallbackCountries=[
{id:'colombia',name:'Colombia',phase:'phase1',route_order:1,dates:'Sep 2026',summary:'Colombia begins The 210 Project with colour, movement and arrival.',current_location:'Medellin',tone:'sage',days:21,status:'upcoming'},
{id:'peru',name:'Peru',phase:'phase1',route_order:2,dates:'Sep / Oct 2026',summary:'Peru is the endurance chapter. Altitude, history and trekking turn the journey into a test of rhythm, patience and resilience.',current_location:'Cusco',tone:'copper',days:24,status:'live'},
{id:'argentina',name:'Argentina',phase:'phase1',route_order:3,dates:'Oct / Nov 2026',summary:'Argentina blends city energy with wilderness.',current_location:'Buenos Aires',tone:'terracotta',days:24,status:'upcoming'},
{id:'brazil',name:'Brazil',phase:'phase1',route_order:4,dates:'Nov / Dec 2026',summary:'Brazil closes the South America act.',current_location:'Rio',tone:'ochre',days:24,status:'upcoming'},
{id:'vietnam',name:'Vietnam',phase:'phase2',route_order:5,dates:'Jan 2027',summary:'Vietnam opens the Asia act.',current_location:'Hanoi',tone:'brick',days:18,status:'upcoming'},
{id:'south-korea',name:'South Korea',phase:'phase2',route_order:6,dates:'Jan / Feb 2027',summary:'South Korea becomes a study in pace and structure.',current_location:'Seoul',tone:'plum',days:14,status:'upcoming'},
{id:'japan',name:'Japan',phase:'phase2',route_order:7,dates:'Feb 2027',summary:'Japan is the detail chapter.',current_location:'Tokyo',tone:'rose',days:21,status:'upcoming'},
{id:'hong-kong',name:'Hong Kong',phase:'phase2',route_order:8,dates:'Mar 2027',summary:'Hong Kong compresses energy into skyline and movement.',current_location:'Hong Kong Island',tone:'wine',days:7,status:'upcoming'},
{id:'singapore',name:'Singapore',phase:'phase2',route_order:9,dates:'Mar 2027',summary:'Singapore closes the Asia act.',current_location:'Marina Bay',tone:'teal',days:7,status:'upcoming'}];
export const fallbackLocations=[{id:'1',country_id:'peru',slug:'cusco',name:'Cusco',date_text:'Oct 2026',summary:'Altitude, history and a slower pace before Machu Picchu.',blog:'Cusco is where the journey becomes physical.\n\n[[photo:example]]\n\nThe altitude makes everything slower, but that slowness becomes useful.',tags:['altitude','history','patience'],hero_image:'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80',sort_order:1}];
export const fallbackMedia=[];export const fallbackSettings={current_country_id:'peru',current_location_slug:'cusco'};
