export const fallbackCountries=[
{id:'colombia',name:'Colombia',phase:'phase1',code:'CO',route_order:1,dates:'Sep 2026',summary:'Colombia begins The 210 Project with colour, movement and arrival.',current_location:'Medellin',highlights:['First solo travel rhythm','Coffee region','Caribbean coast'],tone:'sage',days:21},
{id:'peru',name:'Peru',phase:'phase1',code:'PE',route_order:2,dates:'Sep / Oct 2026',summary:'Peru is the endurance chapter. Altitude, history and trekking turn the journey into a test of rhythm, patience and resilience.',current_location:'Cusco',highlights:['Machu Picchu sunrise','Cusco altitude lesson','Paracas coastline'],tone:'copper',days:24},
{id:'argentina',name:'Argentina',phase:'phase1',code:'AR',route_order:3,dates:'Oct / Nov 2026',summary:'Argentina blends city energy with wilderness: a chapter about scale, long journeys, food, culture and the symbolic edge of the continent.',current_location:'Buenos Aires',highlights:['Buenos Aires evenings','Patagonia hikes','Ushuaia'],tone:'terracotta',days:24},
{id:'brazil',name:'Brazil',phase:'phase1',code:'BR',route_order:4,dates:'Nov / Dec 2026',summary:'Brazil closes the South America act with warmth, rhythm, coastline and reflection before the story turns towards Asia.',current_location:'Rio',highlights:['Rio sunset','Island days','Iguacu Falls'],tone:'ochre',days:24},
{id:'vietnam',name:'Vietnam',phase:'phase2',code:'VN',route_order:5,dates:'Jan 2027',summary:'Vietnam opens the Asia act. Food, movement and sensory overload create a reset after South America.',current_location:'Hanoi',highlights:['Street food','Lanterns','Coastline'],tone:'brick',days:18},
{id:'south-korea',name:'South Korea',phase:'phase2',code:'KR',route_order:6,dates:'Jan / Feb 2027',summary:'South Korea becomes a study in pace, structure, modern culture and the design of everyday movement.',current_location:'Seoul',highlights:['Seoul city rhythm','Markets','Busan coastline'],tone:'plum',days:14},
{id:'japan',name:'Japan',phase:'phase2',code:'JP',route_order:7,dates:'Feb 2027',summary:'Japan is the detail chapter: trains, temples, neon, quiet rituals and the discipline of noticing more.',current_location:'Tokyo',highlights:['Tokyo nights','Kyoto temples','Train journeys'],tone:'rose',days:21},
{id:'hong-kong',name:'Hong Kong',phase:'phase2',code:'HK',route_order:8,dates:'Mar 2027',summary:'Hong Kong compresses energy into skyline, movement, ferries, viewpoints and height.',current_location:'Hong Kong Island',highlights:['Skyline','Ferries','Viewpoints'],tone:'wine',days:7},
{id:'singapore',name:'Singapore',phase:'phase2',code:'SG',route_order:9,dates:'Mar 2027',summary:'Singapore closes the Asia act with design, systems, order, food and the feeling of a city built with intention.',current_location:'Marina Bay',highlights:['Gardens','Hawker centres','Design'],tone:'teal',days:7}
];
export const fallbackLocations=[
{id:'1',country_id:'peru',slug:'cusco',name:'Cusco',date_text:'Oct 2026',summary:'Altitude, history and a slower pace before Machu Picchu.',blog:'Cusco is where the journey becomes physical. The altitude makes everything slower, but that slowness becomes useful.',highlights:['Altitude adjustment','Old town wandering','Preparing for Machu Picchu'],tags:['altitude','history','patience'],hero_image:'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80',sort_order:1},
{id:'2',country_id:'japan',slug:'tokyo',name:'Tokyo',date_text:'Feb 2027',summary:'Neon, trains and a city that rewards attention to detail.',blog:'Tokyo becomes a detail chapter. The city moves quickly, but the archive is about the small systems: signs, stations, food counters and late-night streets.',highlights:['Night streets','Train systems','Food counters'],tags:['curiosity','city','detail'],hero_image:'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80',sort_order:1},
{id:'3',country_id:'brazil',slug:'rio',name:'Rio',date_text:'Dec 2026',summary:'Colour, rhythm and the closing note of South America.',blog:'Rio closes the first act of The 210 Project. The archive here is less about motion and more about presence.',highlights:['Sunset','Beach walks','Closing reflection'],tags:['joy','reflection','coast'],hero_image:'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1200&q=80',sort_order:1}
];
export const fallbackMedia=[];
export const fallbackSettings={current_country_id:'peru',current_location_slug:'cusco'};
